/* eslint-disable */
// Auto-generated by renusify — DO NOT EDIT
import type { DefineComponent } from 'vue'

declare module 'vue' {
  export interface GlobalComponents {
    'rApp': DefineComponent<{
      id: string | number
      rtl: boolean
    }, {}, any>
    'rAvatar': DefineComponent<{
      size: number | string
      elevation: string
      editable: string
      flat: boolean
      tile: boolean
      headers: Record<string, unknown>
    }, {}, any>
    'rBtn': DefineComponent<{
      tag: string
      type: string
      size: string
      label: string | number
      labelClass: string | unknown[] | Record<string, unknown>
      block: boolean
      depressed: boolean
      outlined: boolean
      rounded: boolean
      icon: boolean
      fab: boolean
      text: boolean
      tile: boolean
      disabled: boolean
      readonly: boolean
      loading: boolean
      ariaLabel: string
      activeClass: string
      exactActiveClass: string
      link: boolean
      href: string | Record<string, unknown>
      to: string | Record<string, unknown>
      target: string
    }, {}, any>
    'rBtnConfirm': DefineComponent<{
      hard: boolean
      title: string
      body: string
      cancelText: string
      confirmText: string
    }, {}, any>
    'rBtnGroup': DefineComponent<{
      items: unknown[] | Record<string, unknown>
      icon: boolean
      isSelect: boolean
      exact: boolean
      modelValue: number | string
    }, {}, any>
    'rCalendar': DefineComponent<{
      lang: string
      readonly: boolean
      showHeaders: boolean
      isDateDisabled: ((...args: any[]) => any)
      year: number
      month: number
    }, {}, any>
    'rCard': DefineComponent<{
      flat: boolean
      outlined: boolean
      isRipple: boolean
      activeClass: string
      disabled: boolean
      exactActiveClass: string
      link: boolean
      href: string | Record<string, unknown>
      to: string | Record<string, unknown>
      tag: string
      target: string
    }, {}, any>
    'rCodeEditor': DefineComponent<{
      runnable: boolean
      templateShow: boolean
      scriptShow: boolean
      cssShow: boolean
      template: string
      script: string
      css: string
      scriptSetup: boolean
    }, {}, any>
    'rConfirm': DefineComponent<{
      title: string
      text: string
      cancelText: string
      confirmText: string
      modelValue: boolean
      hard: boolean
    }, {}, any>
    'rContainer': DefineComponent<{
      fullWidth: boolean
      fill: boolean
    }, {}, any>
    'rRow': DefineComponent<{
      dense: boolean
      grid: boolean
      noGutters: boolean
    }, {}, any>
    'rCol': DefineComponent<{
    }, {}, any>
    'rSpacer': DefineComponent<{
    }, {}, any>
    'rDivider': DefineComponent<{
      inset: boolean
      vertical: boolean
    }, {}, any>
    'rContent': DefineComponent<{
      belowHeader: string
      flipped: boolean
      moved: boolean
    }, {}, any>
    'rCropper': DefineComponent<{
      wPH: number | string | unknown[]
      imgSrc: string | Blob
      maxWidth: number
      showCropped: boolean
      getBlob: boolean
      selectImg: boolean
    }, {}, any>
    'rFloat': DefineComponent<{
      bordered: boolean
      disableZoom: boolean
      disableMove: boolean
      trnsfrmOrigin: Record<string, unknown>
      zoom: number
      maxZoom: number
      minZoom: number
    }, {}, any>
    'rForm': DefineComponent<{
      modelValue: boolean
    }, {}, any>
    'rInput': DefineComponent<{
      id: string
      icon: string
      preIcon: string
      msg: string
      label: string
      placeholder: string
      modelValue: string | boolean | number | unknown[] | Record<string, unknown>
      active: boolean
      labelActive: boolean
      hide: boolean
      disabled: boolean
      readonly: boolean
      error: boolean
      autofocus: boolean
      ltr: boolean
      rules: unknown[] | ((...args: any[]) => any)
      validateOnBlur: boolean
    }, {}, any>
    'rColorInput': DefineComponent<{
      modelValue: string
      format: string
    }, {}, any>
    'rDateInput': DefineComponent<{
      modelValue: string | unknown[]
      lang: string
      withTime: boolean
      rangeMode: boolean
      isDateDisabled: ((...args: any[]) => any)
    }, {}, any>
    'rFileInput': DefineComponent<{
      uploadLink: string
      accept: string
      size: number
      wPH: number | string | unknown[]
      maxFileSize: number
      modelValue: unknown[]
      meta: unknown[]
      metaRequired: boolean
    }, {}, any>
    'rTelInput': DefineComponent<{
      type: string
      modelValue: string | number
      defaultCountry: string
      required: boolean
      select: boolean
    }, {}, any>
    'rJsonInput': DefineComponent<{
      keyLabel: string
      valueLabel: string
      modelValue: Record<string, unknown> | unknown[]
      valueType: string
      template: Record<string, unknown>
      baseArray: boolean
      disableAdd: boolean
      disableEditKey: boolean
      disableDel: boolean
      translate: boolean
    }, {}, any>
    'rTextEditor': DefineComponent<{
      uploadLink: string
      modelValue: any
    }, {}, any>
    'rTextEditorPreview': DefineComponent<{
    }, {}, any>
    'rTimeInput': DefineComponent<{
      disableTime: ((...args: any[]) => any)
      withSec: boolean
      is24Hour: boolean
      noOverlay: boolean
      modelValue: string
    }, {}, any>
    'rTimeRangeInput': DefineComponent<{
      withSec: boolean
      noOverlay: boolean
      modelValue: unknown[]
    }, {}, any>
    'rUniqueInput': DefineComponent<{
      link: string
      modelValue: string
      headers: Record<string, unknown>
    }, {}, any>
    'rAddressInput': DefineComponent<{
      required: boolean
      stepShow: boolean
      allowCountries: unknown[]
      hideCountry: boolean
      hideState: boolean
      hideCity: boolean
      hideZipCode: boolean
      hideStreet: boolean
      readonly: boolean
      baseUrl: string
      defaultCountry: Record<string, unknown>
      modelValue: Record<string, unknown>
    }, {}, any>
    'rCamInput': DefineComponent<{
      uploadLink: string
      width: string | number
      height: string | number
      audio: boolean
      video: boolean
      modelValue: unknown[]
      size: number
      headers: Record<string, unknown>
    }, {}, any>
    'rCheckInput': DefineComponent<{
      type: string
      name: string
      link: string
      modelValue: string | number
      headers: Record<string, unknown>
    }, {}, any>
    'rCheckboxInput': DefineComponent<{
      label: string
      readonly: boolean
      rounded: boolean
      modelValue: boolean
      size: string
    }, {}, any>
    'rGroupInput': DefineComponent<{
      itemKey: string
      modelValue: unknown[]
      size: number
      disableAdd: boolean
      translate: boolean
      template: Record<string, unknown>
      addBtnClass: string
    }, {}, any>
    'rMaskInput': DefineComponent<{
      modelValue: string
      mask: string
      required: boolean
      maskedVal: boolean
    }, {}, any>
    'rNumberInput': DefineComponent<{
      modelValue: string
      step: number
      split: number
      min: number
      max: number
      isFloat: boolean
    }, {}, any>
    'rPasswordInput': DefineComponent<{
      modelValue: string | number
      hideRequirements: boolean
      lowerCase: boolean
      upperCase: boolean
      specialChar: boolean
      number: boolean
      minLength: number
      autocomplete: string
    }, {}, any>
    'rRadioInput': DefineComponent<{
      items: unknown[]
      text: string
      rounded: boolean
      justValue: boolean
      translate: boolean
      modelValue: string | number | Record<string, unknown>
    }, {}, any>
    'rRangeInput': DefineComponent<{
      modelValue: number | unknown[]
      min: number
      max: number
      color: string
      step: number
      tooltipAlways: boolean
      disabled: boolean
      isRange: boolean
    }, {}, any>
    'rRatingInput': DefineComponent<{
      count: number
      size: string
      modelValue: number
      readonly: boolean
    }, {}, any>
    'rSelectInput': DefineComponent<{
      searchLink: string
      type: string
      text: string
      value: string
      disableSearch: boolean
      items: unknown[]
      modelValue: string | number | unknown[] | Record<string, unknown>
      tags: boolean
      multiple: boolean
      justValue: boolean
      openToTop: boolean
      translate: boolean
      firstSelect: boolean
      noFloat: boolean
      modal: boolean
      auto: string
      headers: Record<string, unknown>
    }, {}, any>
    'rSwitchInput': DefineComponent<{
      label: string
      label2: string
      modelValue: boolean | string
    }, {}, any>
    'rTextArea': DefineComponent<{
      noResize: boolean
      modelValue: string | number
      rows: string | number
    }, {}, any>
    'rTextInput': DefineComponent<{
      type: string
      modelValue: string | number
    }, {}, any>
    'rUnitInput': DefineComponent<{
      type: string
      units: unknown[]
    }, {}, any>
    'rFormCreator': DefineComponent<{
      url: string
      title: string
      autoSend: boolean
      redirect: string
      method: string
      options: Record<string, unknown> | unknown[]
    }, {}, any>
    'rIcon': DefineComponent<{
      width: string
      height: string
      disabled: boolean
      exact: boolean
    }, {}, any>
    'rImg': DefineComponent<{
      src: string
      preview: string
      alt: string
      lazy: string
      width: string | number
      height: string | number
      query: string
      autoSrcset: boolean
      autoSize: boolean
      hoverZoom: boolean
      hoverDark: boolean
      isSvg: boolean
      svgCache: number
      wPH: number
    }, {}, any>
    'rInfinite': DefineComponent<{
      url: string
      query: Record<string, unknown>
      noItemMsg: string
      distanceLoad: number
      headers: Record<string, unknown>
      isChat: boolean
      height: string
      live: boolean
      liveTimer: number
    }, {}, any>
    'rMap': DefineComponent<{
      modelValue: unknown[]
      height: string
      zoom: number
      center: unknown[]
      markers: unknown[]
      searchBox: boolean
      zoomControl: boolean
      layerControl: boolean
      meLocation: boolean
      disableMove: boolean
      darkMode: boolean
      mapImageMarker: string
      mapImageLayers: string
    }, {}, any>
    'rMapSelect': DefineComponent<{
      modelValue: unknown[]
      height: string
      zoom: number
      mapImageMarker: string
    }, {}, any>
    'rMapRoute': DefineComponent<{
      modelValue: Record<string, unknown>
      by: string
      height: string
      marginTime: number
      color: unknown[]
      maxPoints: number
      darkMode: boolean
      editable: boolean
    }, {}, any>
    'rMenu': DefineComponent<{
      modelValue: string | number | Record<string, unknown>
      label: string
      icon: string
      value: string
      justValue: boolean
      reverse: boolean
      overlay: boolean
      items: unknown[]
    }, {}, any>
    'rModal': DefineComponent<{
      modelValue: boolean
      position: string
      noOverlay: boolean
      fullWidth: boolean
      fullHeight: boolean
      maxWidth: string
      maxHeight: string
      minWidth: boolean
      noClosable: boolean
      noCloseBtn: boolean
      routeHistory: string
      animation: string
    }, {}, any>
    'rNotify': DefineComponent<{
      permanent: any
      top: boolean
      left: boolean
      status: string
      width: string
      timeout: number
    }, {}, any>
    'rProgressCircle': DefineComponent<{
      indeterminate: boolean
      showPercent: boolean
      rotate: number | string
      size: number | string
      width: number | string
      modelValue: number | string
    }, {}, any>
    'rProgressLine': DefineComponent<{
      modelValue: number | string
      color: string
      progressStyle: string | Record<string, unknown> | unknown[]
      showPercent: boolean
      outlined: boolean
      rounded: boolean
      showBackground: boolean
      size: string
    }, {}, any>
    'rSearchBox': DefineComponent<{
      closable: boolean
      notFoundMsg: string
      label: string
      url: string
      btnAttr: Record<string, unknown>
      query: string
      modelValue: string | number
      noOverlay: boolean
      openToTop: boolean
      categories: unknown[]
      headers: Record<string, unknown>
    }, {}, any>
    'rSlider': DefineComponent<{
      slides: unknown[]
      speed: number
      wPH: number
      startIndex: number
      autoplay: boolean
      progress: boolean
      arrow: boolean
      dots: boolean
      appear: boolean
      slidesClass: string | Record<string, unknown> | unknown[]
      mode: string
      transitionRight: string
      transitionLeft: string
    }, {}, any>
    'rSwiper': DefineComponent<{
      items: unknown[]
      widthItem: number
      dots: boolean
      numShow: number | Record<string, unknown>
    }, {}, any>
    'rTable': DefineComponent<{
      transition: string
      keyItem: string | ((...args: any[]) => any)
      thin: boolean
      responsive: boolean
      translate: boolean
      editable: boolean
      tableKey: string
      stripped: boolean
      bordered: boolean
      sortable: Record<string, unknown>
      fixedHeader: boolean
      fixedFirstColumn: boolean
      headers: unknown[]
      items: unknown[]
    }, {}, any>
    'rTableCrud': DefineComponent<{
      link: string
      actions: unknown[]
    }, {}, any>
    'rTimeAgo': DefineComponent<{
      time: any
      noTrans: boolean
      liveTime: number
      live: boolean
    }, {}, any>
    'rTour': DefineComponent<{
      steps: unknown[]
      canFinish: boolean
      abortOnNotFound: boolean
      delay: number
    }, {}, any>
    'rTree': DefineComponent<{
      modelValue: Record<string, unknown>
      link: string
      searchLink: string
      sortBy: string
      gen: string
      selected: string
      rotate: boolean
      expand: boolean
      childsName: string
      headers: Record<string, unknown>
    }, {}, any>
    'rHighlight': DefineComponent<{
      name: string
      src: string
      hideLineNumbers: boolean
      lang: string
    }, {}, any>
  }
}

export {}
