/* eslint-disable */
// Auto-generated by renusify — DO NOT EDIT
import type { ObjectDirective } from 'vue'

declare module '@vue/runtime-dom' {
  export interface GlobalDirectives {
    vAnimate: ObjectDirective
    vClickOutside: ObjectDirective
    vDrag: ObjectDirective
    vIntersect: ObjectDirective
    vMask: ObjectDirective
    vParallax: ObjectDirective
    vRipple: ObjectDirective
    vScroll: ObjectDirective
    vSortable: ObjectDirective
    vTouch: ObjectDirective
    vTitle: ObjectDirective
  }
}

// Named exports for manual import
export declare const animate: ObjectDirective
export declare const clickOutside: ObjectDirective
export declare const drag: ObjectDirective
export declare const intersect: ObjectDirective
export declare const mask: ObjectDirective
export declare const parallax: ObjectDirective
export declare const ripple: ObjectDirective
export declare const scroll: ObjectDirective
export declare const sortable: ObjectDirective
export declare const touch: ObjectDirective
export declare const title: ObjectDirective

export {}
