// generate-types.mjs
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { VueComponentAPIParser } from './parser.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
const componentsDir = path.join(rootDir, 'components');
const directivesDir = path.join(rootDir, 'directive');
const typesDir = path.join(rootDir, 'types');

async function fileExists(p) {
  try { await fs.access(p); return true; } catch { return false; }
}

async function findVueFile(jsRelativePath) {
  const cleanPath = jsRelativePath.replace(/^\.\//, '');
  const fullPath = path.join(componentsDir, cleanPath);
  const dir = path.dirname(fullPath);
  const baseName = path.basename(fullPath, '.js');
  
  const candidates = baseName === 'index'
    ? [path.join(dir, 'index.vue'), path.join(dir, `${path.basename(dir)}.vue`)]
    : [path.join(dir, `${baseName}.vue`)];
  
  for (const c of candidates) {
    if (await fileExists(c)) return c;
  }
  return null;
}

/**
 * Parse directive/index.js to extract directive names
 */
async function parseDirectives() {
  const directives = [];
  const indexPath = path.join(directivesDir, 'index.js');
  
  if (!await fileExists(indexPath)) {
    console.warn('⚠️ directive/index.js not found, skipping directive types');
    return directives;
  }
  
  try {
    const content = await fs.readFile(indexPath, 'utf-8');
    // Match: export * as directiveName from './path/index.js'
    const exportRegex = /export\s+\*\s+as\s+(\w+)\s+from\s+['"]([^'"]+)['"]/g;
    let match;
    
    while ((match = exportRegex.exec(content)) !== null) {
      const name = match[1];
      const relativePath = match[2];
      
      directives.push({
        name, // e.g., 'animate', 'title'
        exportName: name.startsWith('v') || name.startsWith('V') ? name : `v${name.charAt(0).toUpperCase()}${name.slice(1)}`, // e.g., 'vAnimate', 'vTitle'
        relativePath
      });
    }
    
    console.log(`  ✓ Found ${directives.length} directives`);
  } catch (err) {
    console.error(`  ✗ Failed to parse directives: ${err.message}`);
  }
  
  return directives;
}

/**
 * Generate directive.d.ts content
 */
function generateDirectiveDts(directives) {
  let out = '/* eslint-disable */\n';
  out += '// Auto-generated by renusify — DO NOT EDIT\n';
  out += "import type { ObjectDirective } from 'vue'\n\n";
  
  // Global directives registration for Vue template type checking
  out += "declare module '@vue/runtime-dom' {\n";
  out += '  export interface GlobalDirectives {\n';
  
  for (const d of directives) {
    out += `    ${d.exportName}: ObjectDirective\n`;
  }
  
  out += '  }\n}\n\n';
  
  // Named exports for manual import usage
  out += '// Named exports for manual import\n';
  for (const d of directives) {
    out += `export declare const ${d.name}: ObjectDirective\n`;
  }
  
  out += '\nexport {}\n';
  return out;
}

/**
 * Extract raw prop value from defineProps block with proper brace balancing
 */
function extractPropValue(block, startIndex) {
  let depth = 0;
  let inString = false;
  let stringChar = '';
  let i = startIndex;
  
  while (i < block.length) {
    const ch = block[i];
    const prev = i > 0 ? block[i - 1] : '';
    
    // Handle string literals
    if (!inString && (ch === "'" || ch === '"' || ch === '`')) {
      inString = true;
      stringChar = ch;
      i++;
      continue;
    }
    if (inString && ch === stringChar && prev !== '\\') {
      inString = false;
      i++;
      continue;
    }
    if (inString) { i++; continue; }
    
    // Track depth for {}, [], ()
    if (ch === '{' || ch === '[' || ch === '(') depth++;
    else if (ch === '}' || ch === ']' || ch === ')') {
      depth--;
      if (depth < 0) return { value: block.substring(startIndex, i).trim(), endIdx: i };
    }
    // End at top-level comma
    else if (ch === ',' && depth === 0) {
      return { value: block.substring(startIndex, i).trim(), endIdx: i };
    }
    i++;
  }
  return { value: block.substring(startIndex).trim(), endIdx: block.length };
}

/**
 * Parse props using improved logic that handles complex defaults
 */
function parsePropsImproved(scriptContent) {
  const props = [];
  
  // Match defineProps with object syntax: defineProps({ ... }) or defineProps<{ ... }>()
  const propsMatch = scriptContent.match(/defineProps\s*(?:<\s*\{([\s\S]*?)\}\s*>|\(\s*\{([\s\S]*?)\}\s*\))/);
  if (!propsMatch) return props;
  
  const block = (propsMatch[1] || propsMatch[2]).trim();
  let i = 0;
  
  while (i < block.length) {
    // Skip whitespace and comments
    while (i < block.length && /\s/.test(block[i])) i++;
    if (i >= block.length) break;
    
    // Skip single-line comments
    if (block.slice(i, i + 2) === '//') {
      i = block.indexOf('\n', i);
      if (i === -1) break;
      continue;
    }
    // Skip multi-line comments
    if (block.slice(i, i + 2) === '/*') {
      const endComment = block.indexOf('*/', i + 2);
      i = endComment === -1 ? block.length : endComment + 2;
      continue;
    }
    
    // Match prop name: propName? :
    const nameMatch = block.slice(i).match(/^([a-zA-Z_]\w*)(\??)\s*:\s*/);
    if (!nameMatch) { i++; continue; }
    
    const name = nameMatch[1];
    const optional = nameMatch[2] === '?';
    const valueStart = i + nameMatch[0].length;
    
    // Extract the full value with balanced braces
    const { value, endIdx } = extractPropValue(block, valueStart);
    
    props.push({ name, optional, rawValue: value });
    
    i = endIdx + 1;
    // Skip comma
    while (i < block.length && (block[i] === ',' || /\s/.test(block[i]))) i++;
  }
  
  return props;
}

/**
 * Extract TypeScript type from Vue prop raw value
 */
function extractTypeFromValue(rawValue) {
  let v = rawValue.trim();
  
  // Case 1: Options API object { type: ..., default: ..., ... }
  if (v.startsWith('{') && v.endsWith('}')) {
    const inner = v.slice(1, -1).trim();
    
    // Find type: value with proper brace handling
    const typeMatch = findPropertyWithValue(inner, 'type');
    if (typeMatch) {
      return convertVueTypeToTS(typeMatch);
    }
    return 'any';
  }
  
  // Case 2: Direct type reference or union
  return convertVueTypeToTS(v);
}

/**
 * Find a property value in an object string with brace awareness
 */
function findPropertyWithValue(objStr, propName) {
  const regex = new RegExp(`(?:^|,)\\s*${propName}\\s*:\\s*`, 'i');
  const match = objStr.match(regex);
  if (!match) return null;
  
  const startIdx = match.index + match[0].length;
  const { value } = extractPropValue(objStr, startIdx);
  return value;
}

/**
 * Convert Vue constructor types to TypeScript types
 */
function convertVueTypeToTS(value) {
  let v = value.trim();
  
  // Handle array of constructors: [String, Number]
  if (v.startsWith('[') && v.endsWith(']')) {
    const inner = v.slice(1, -1);
    const types = splitByCommaAtDepth(inner).map(t => mapSingleVueType(t.trim()));
    return types.filter(t => t).join(' | ');
  }
  
  // Handle generic types, unions, intersections
  if (v.includes('|') || v.includes('&')) {
    const parts = splitByOperator(v, ['|', '&']);
    return parts.map(p => mapSingleVueType(p.trim())).join(' | ');
  }
  
  return mapSingleVueType(v);
}

/**
 * Split string by comma, respecting nested braces/brackets/parens
 */
function splitByCommaAtDepth(str) {
  const result = [];
  let current = '';
  let depth = 0;
  let inString = false;
  let stringChar = '';
  
  for (let i = 0; i < str.length; i++) {
    const ch = str[i];
    const prev = i > 0 ? str[i - 1] : '';
    
    if (!inString && (ch === "'" || ch === '"' || ch === '`')) {
      inString = true;
      stringChar = ch;
      current += ch;
      continue;
    }
    if (inString && ch === stringChar && prev !== '\\') {
      inString = false;
      current += ch;
      continue;
    }
    if (inString) {
      current += ch;
      continue;
    }
    
    if (ch === '{' || ch === '[' || ch === '(') depth++;
    else if (ch === '}' || ch === ']' || ch === ')') depth--;
    else if (ch === ',' && depth === 0) {
      result.push(current.trim());
      current = '';
      continue;
    }
    current += ch;
  }
  if (current.trim()) result.push(current.trim());
  return result;
}

/**
 * Split by operator (| or &) at top level
 */
function splitByOperator(str, operators) {
  const result = [];
  let current = '';
  let depth = 0;
  let inString = false;
  let stringChar = '';
  
  for (let i = 0; i < str.length; i++) {
    const ch = str[i];
    const prev = i > 0 ? str[i - 1] : '';
    
    if (!inString && (ch === "'" || ch === '"' || ch === '`')) {
      inString = true;
      stringChar = ch;
      current += ch;
      continue;
    }
    if (inString && ch === stringChar && prev !== '\\') {
      inString = false;
      current += ch;
      continue;
    }
    if (inString) {
      current += ch;
      continue;
    }
    
    if (ch === '{' || ch === '[' || ch === '(') depth++;
    else if (ch === '}' || ch === ']' || ch === ')') depth--;
    else if (operators.includes(ch) && depth === 0) {
      result.push(current.trim());
      current = '';
      continue;
    }
    current += ch;
  }
  if (current.trim()) result.push(current.trim());
  return result;
}

/**
 * Map single Vue type to TypeScript type
 */
function mapSingleVueType(t) {
  if (!t) return 'any';
  
  // Remove quotes
  t = t.replace(/^['"`\s]+|['"`\s]+$/g, '');
  
  const typeMap = {
    'String': 'string',
    'Number': 'number', 
    'Boolean': 'boolean',
    'Object': 'Record<string, unknown>',
    'Array': 'unknown[]',
    'Function': '((...args: any[]) => any)',
    'Date': 'Date',
    'Blob': 'Blob',
    'File': 'File',
    'Promise': 'Promise<unknown>',
    'RegExp': 'RegExp',
    'Symbol': 'symbol',
    'Error': 'Error',
    'null': 'null',
    'undefined': 'undefined',
    'any': 'any',
    'unknown': 'unknown',
    'void': 'void',
    'never': 'never'
  };
  
  // Handle TypeScript generics (keep as-is)
  if (/<.*>/.test(t) || t.includes('=>')) {
    return t;
  }
  
  return typeMap[t] || t;
}

/**
 * Parse emits from script content
 */
function parseEmits(scriptContent) {
  const emits = [];
  
  // Match defineEmits with array or object syntax
  const emitsMatch = scriptContent.match(/defineEmits\s*(?:<\s*\{([\s\S]*?)\}\s*>|\(\s*(\[[\s\S]*?\]|\{[\s\S]*?\})\s*\))/);
  if (!emitsMatch) return emits;
  
  const block = (emitsMatch[1] || emitsMatch[2]).trim();
  
  // Array syntax: ['event1', 'event2']
  if (block.startsWith('[')) {
    const names = block.match(/['"]([\w:-]+)['"]/g);
    if (names) {
      names.forEach(n => {
        const name = n.replace(/['"]/g, '');
        emits.push({ name });
      });
    }
  }
  // Object syntax: { (e: 'event'): (payload: Type) => void }
  else if (block.startsWith('{')) {
    const eventNames = block.match(/['"]?([\w:-]+)['"]?\s*:/g);
    if (eventNames) {
      eventNames.forEach(e => {
        const name = e.replace(/['"]?\s*:/g, '').trim();
        if (name && !name.startsWith('(')) {
          emits.push({ name });
        }
      });
    }
  }
  
  return emits;
}

/**
 * Generate components.d.ts content
 */
function generateDts(components) {
  let out = '/* eslint-disable */\n';
  out += '// Auto-generated by renusify — DO NOT EDIT\n';
  out += "import type { DefineComponent } from 'vue'\n\n";
  out += "declare module 'vue' {\n";
  out += '  export interface GlobalComponents {\n';

  for (const c of components) {
    out += `    '${c.name}': DefineComponent<{\n`;
    for (const p of c.props) {
      const opt = p.optional ? '?' : '';
      const tsType = extractTypeFromValue(p.rawValue);
      out += `      ${p.name}${opt}: ${tsType}\n`;
    }
    out += '    }, {}, any>\n';
  }

  out += '  }\n}\n\nexport {}\n';
  return out;
}

/**
 * Generate web-types.json content
 */
function generateWebTypes(components) {
  return {
    "$schema": "https://raw.githubusercontent.com/AmadeusITGroup/WebTypes/master/schema/web-types.json",
    "framework": "vue",
    "name": "renusify",
    "version": "3.1.1",
    "contributions": {
      "html": {
        "vue-components": components.map(c => ({
          "name": c.name,
          "attributes": c.props.map(p => ({
            "name": p.name,
            "value": { "type": extractTypeFromValue(p.rawValue) },
            "required": !p.optional
          })),
          "events": c.emits.map(e => ({ "name": e.name }))
        }))
      }
    }
  };
}

/**
 * Generate Zed IDE snippets for Vue 3 + Renusify
 */
function generateZedSnippets(components) {
  const snippets = {
    ...Object.fromEntries(
      components.map(c => [
        `renusify_${c.name}`,
        {
          "prefix": `${c.name.toLowerCase()}`,
          "body": [
            `<${c.name}${c.props.length > 0 ? '\n' : ''}${
              c.props.map(p => 
                `  ${p.name}=${p.optional ? '?' : ''}"${'${1:' + p.name + '}'}"`
              ).join('\n')
            }${c.props.length > 0 ? '\n' : ''}/>`,
            "${0}"
          ].filter(Boolean),
          "description": `Renusify <${c.name}> component`
        }
      ])
    )
  };

  return snippets;
}

async function main() {
  console.log('🔍 Scanning Renusify components...\n');
  
  const indexPath = path.join(componentsDir, 'index.js');
  const indexContent = await fs.readFile(indexPath, 'utf-8');
  const exportRegex = /export\s+\*\s+as\s+(\w+)\s+from\s+['"]([^'"]+)['"]/g;
  
  const components = [];
  let match;
  
  while ((match = exportRegex.exec(indexContent)) !== null) {
    const alias = match[1];
    const jsPath = match[2];
    const vuePath = await findVueFile(jsPath);
    
    if (!vuePath) {
      console.warn(`  ⚠️ ${alias}: No .vue file found`);
      continue;
    }
    
    try {
      const vueContent = await fs.readFile(vuePath, 'utf-8');
      
      // Use the parser class for comprehensive API extraction
      const api = VueComponentAPIParser.parse(vueContent);
      
      // Fallback to improved parser if class doesn't extract props
      const props = api.props.length > 0 
        ? api.props.map(p => ({ 
            name: p.name, 
            optional: !p.type?.includes('required') && p.type?.endsWith('?'),
            rawValue: p.type || 'any' 
          }))
        : parsePropsImproved(vueContent);
      
      const emits = api.emits.length > 0 ? api.emits : parseEmits(vueContent);
      
      components.push({
        name: alias,
        props,
        emits
      });
      
      console.log(`  ✓ ${alias}: ${props.length} props, ${emits.length} emits`);
    } catch (err) {
      console.error(`  ✗ ${alias}: ${err.message}`);
      // Fallback to simple parser on error
      try {
        const vueContent = await fs.readFile(vuePath, 'utf-8');
        const props = parsePropsImproved(vueContent);
        const emits = parseEmits(vueContent);
        
        components.push({ name: alias, props, emits });
        console.log(`  ✓ ${alias} (fallback): ${props.length} props`);
      } catch (err2) {
        console.error(`  ✗ ${alias} (fallback failed): ${err2.message}`);
      }
    }
  }
  
  console.log(`\n✅ Parsed ${components.length} components.\n`);
  
  if (components.length === 0) {
    console.error('❌ No components found. Check your index.js exports.');
    process.exit(1);
  }
  
  await fs.mkdir(typesDir, { recursive: true });
  
  // Generate components.d.ts
  const dtsContent = generateDts(components);
  await fs.writeFile(path.join(typesDir, 'components.d.ts'), dtsContent);
  console.log('✓ Generated types/components.d.ts');
  
  // Generate web-types.json
  const webTypesContent = generateWebTypes(components);
  await fs.writeFile(path.join(typesDir, 'web-types.json'), JSON.stringify(webTypesContent, null, 2));
  console.log('✓ Generated types/web-types.json');

  // ✨ Generate directive.d.ts
  const directives = await parseDirectives();
  if (directives.length > 0) {
    const directiveDts = generateDirectiveDts(directives);
    await fs.writeFile(path.join(typesDir, 'directive.d.ts'), directiveDts);
    console.log('✓ Generated types/directive.d.ts');
  }

  // ✨ Generate Zed snippets
  const snippets = generateZedSnippets(components);
  const snippetsPath = path.join(rootDir, 'snippets', 'zed.json');
  await fs.mkdir(path.dirname(snippetsPath), { recursive: true });
  await fs.writeFile(snippetsPath, JSON.stringify(snippets, null, 2));
  console.log('✓ Generated snippets/zed.json for Zed IDE');
  
  console.log('\n🎉 Done! Type definitions are ready.');
}

main().catch(err => { 
  console.error('💥 Fatal error:', err); 
  process.exit(1); 
});